package by.epam.akulich.gym.dao;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * The functional interface handles a {@link ResultSet}.
 *
 * @param <T> of the input to the handler
 * @author Andrey Akulich
 */
@FunctionalInterface
public interface ResultHandler<T> {

    /**
     * Handles {@link ResultSet} and return selected data type.
     * @param resultSet a table of data representing a database result set, which
     *                  is usually generated by executing a statement that queries the database.
     * @return handled data type
     * @throws SQLException if a database access error occurs
     */
    T handle(ResultSet resultSet) throws SQLException;
}
