package dao;

import connection.ConnectionPool;
import connection.ProxyConnection;
import connection.exception.ConnectionException;
import dao.exception.DAOException;
import dao.exception.ExecutorException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * DAO abstract class to interact with appointment tables of database.
 *
 * @param <T> type of concrete appointment
 * @author Andrey Akulich
 */
public abstract class AppointmentDAO<T> {

    /**
     * Instance of {@link Executor}
     */
    private Executor executor = Executor.getInstance();

    /**
     * @return SQL query for selecting all appointments.
     */
    protected abstract String getAllQuery();

    /**
     * @return SQL query for selecting all appointments
     * according booking {@link entity.Booking} identifier
     */
    protected abstract String getByBookingIdQuery();

    /**
     * @return SQL query for inserting new appointments
     */
    protected abstract String addAppointmentQuery();

    /**
     * Handles {@link ResultSet} of concrete appointment and
     * sets result in param list.
     *
     * @param list a list to set appointment
     * @param resultSet a table of data representing a database result set, which
     *                  is usually generated by executing a statement that queries the database.
     * @throws SQLException if a database access error occurs or this method is
     * called on a closed result set
     */
    protected abstract void handleAllResult(List<T> list, ResultSet resultSet) throws SQLException;

    /**
     * Handles {@link ResultSet} of concrete appointment according {@link entity.Booking}
     * identifier then sets result in param list.
     *
     * @param list a list to set appointment
     * @param resultSet a table of data representing a database result set, which
     *                  is usually generated by executing a statement that queries the database.
     * @throws SQLException if a database access error occurs or this method is
     * called on a closed result set
     */
    protected abstract void handleByBookingIdResult(List<T> list, ResultSet resultSet) throws SQLException;

    /**
     *
     *
     * @param bookingId {@link entity.Booking} identifier
     * @param t a type of appointment
     * @param statement an object that represents a precompiled SQL statement
     * @throws SQLException if a database access error occurs or this method is
     * called on a closed result set
     */
    protected abstract void handleAdd(int bookingId, T t, PreparedStatement statement) throws SQLException;

    /**
     * Returns a list of all appointments.
     *
     * @return a list of appointments
     * @throws DAOException if the query failed
     */
    public List<T> getAll() throws DAOException {
        try {
            return executor.executeQuery(getAllQuery(), resultSet -> {
                List<T> ts = new ArrayList<>();
                while (resultSet.next()) {
                    handleAllResult(ts, resultSet);
                }
                return ts;
            });
        } catch (ExecutorException e) {
            throw new DAOException(e);
        }
    }

    /**
     * Returns a list of all appointments according {@link entity.Booking}
     * identifier.
     *
     * @param userId {@link entity.User} identifier
     * @return a list of all appointments according {@link entity.Booking}
     * identifier.
     * @throws DAOException if the query failed
     */
    public List<T> getByBookingId(int userId) throws DAOException {
        try {
            return executor.executeQuery(getByBookingIdQuery(), statement -> {
                statement.setInt(1, userId);
            }, resultSet -> {
                List<T> ts = new ArrayList<>();
                while (resultSet.next()){
                    handleByBookingIdResult(ts, resultSet);
                }
                return ts;
            });
        } catch (ExecutorException e) {
            throw new DAOException(e);
        }
    }

    /**
     * Adds new appointment to database.
     *
     * @param bookingId {@link entity.Booking} identifier
     * @param list a list of appointments
     * @throws DAOException if the query failed
     */
    public void addAppointment(int bookingId, List<T> list) throws DAOException {
        ConnectionPool pool = ConnectionPool.getInstance();
        ProxyConnection connection = null;
        try {
            connection = pool.getConnection();
            connection.setAutoCommit(false);
            PreparedStatement statement = connection.prepareStatement(addAppointmentQuery());
            for (T t : list) {
                handleAdd(bookingId, t, statement);
            }
            statement.executeBatch();
        } catch (SQLException | ConnectionException e) {
            if (connection != null) {
                connection.rollback();
            }
            throw new DAOException(e);
        } finally {
            if (connection != null) {
                connection.setAutoCommit(true);
                connection.close();
            }
        }
    }
}
