package dao;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * This functional interface parses a {@link ResultSet}.
 *
 * @param <T> of the input to the handler
 * @author Andrey Akulich
 */
@FunctionalInterface
public interface ResultHandler<T> {

    /**
     * Parses a {@link ResultSet}.
     * @param resultSet a table of data representing a database result set, which
     *                  is usually generated by executing a statement that queries the database.
     * @return parsed data type
     * @throws SQLException if a database access error occurs
     */
    T handle(ResultSet resultSet) throws SQLException;
}
