package connection;

import connection.exception.ConnectionException;
import connection.exception.DBFinishException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class ProxyConnection implements AutoCloseable {

    private static final Logger LOGGER = LogManager.getLogger(ProxyConnection.class.getSimpleName());
    private Connection connection;

    public ProxyConnection(Connection connection) {
        this.connection = connection;
    }

    @Override
    public void close() {
        ConnectionPool pool = ConnectionPool.getInstance();
        pool.returnConnection(this);
    }

    public void finish() {
        try {
            connection.close();
        } catch (SQLException e) {
            LOGGER.error("Can't close connection.", e);
            throw new DBFinishException();
        }
    }

    public Statement createStatement() throws ConnectionException {
        try {
            return connection.createStatement();
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }

    public PreparedStatement prepareStatement(String sql) throws ConnectionException {
        try {
            return connection.prepareStatement(sql);
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }

    public void setAutoCommit(boolean autoCommit) throws ConnectionException {
        try {
            connection.setAutoCommit(autoCommit);
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }

    public void commit() throws ConnectionException {
        try {
            connection.commit();
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }

    public void rollback() throws ConnectionException {
        try {
            connection.rollback();
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws ConnectionException {
        try {
            return connection.prepareStatement(sql, columnNames);
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws ConnectionException {
        try {
            return connection.prepareStatement(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            throw new ConnectionException(e);
        }
    }
}
